### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by sonalmahajan01** [Thamaraiselvam/Linkedin-Api#1]
Hi,
I tried to implement your code but I am getting a blank screen when i calling demo.php using the following url.
https://staging1.XXXXXXcom/staging-sonal/trackvox_1.5/demo.php.
Please help me. I have been trying since long with no result.

**Comment by sonalmahajan01** [comment]
I finally managed to make the above piece of code work. Seems, in callback url linkedIn sometimes rejects too many escape characters, so i shortened the callback url and it worked. But this code uses oauth1 and I read we should use oAuth2. What changes should i make in the existing code to migrate it to oAuth2? Please do suggest.

**Comment by thamaraiselvam** [comment]
Hi, 
Try to run auth.php first , that will be redirect you to demo.php

**Comment by thamaraiselvam** [comment]
![capture](https://cloud.githubusercontent.com/assets/6559664/6818634/7d625ed4-d2d9-11e4-87c8-27f03f4e4fb3.PNG)

**Comment by sonalmahajan01** [comment]
yes, thank you for the prompt reply. I did that and some other changes in my env and it gave me the access token and key. I have to get the companies for which user is admin and then  pull the company data. I would really appreciate if you have thing related to that. Also I need to make some POST and DELETE requests. By default, it takes the GET request, but will it work the same for others also?

**Comment by thamaraiselvam** [comment]
http://stackoverflow.com/questions/8593144/how-to-retrieve-all-possible-information-about-a-linkedin-account-api-using-c

this might help you for pulling company data

**Comment by sonalmahajan01** [comment]
Hi,

Thanks for the reply but I don’t want the details of the person as say but I have to develop an app which manages pages which user has access to. I could get the user key and secret using your code but am not able to get the company details. I have to pull data from the pages and push data.

I have been trying to get around this since 1 week depending on their documentation but after no success …so started looking around. Please do let me know if u know anything regarding this.

Also, in the LinkedIn class, I need to add get() post() and delete() functions for executing the above commands. Any idea regarding that.

Thanks.
